---
- name: Include Netplan vars
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_facts.distribution}}-{{ansible_facts.distribution_major_version}}.yml'
        - '{{ansible_facts.distribution}}.yml'
        - '{{ansible_facts.os_family}}.yml'
        - default.yml
      paths:
        - 'vars'
  when: network.default is defined and network.default

- name: Move content of INTERFACE to the correct interface name.
  set_fact:
    network: "{{ network | combine({'ethernets': { ansible_facts.default_ipv4.interface : network['ethernets']['INTERFACE'] }}, recursive=True) }}"
  when: network.ethernets is defined and network.ethernets.INTERFACE is defined

- name: Remove the INTERFACE key 
  set_fact:
    network: "{% set removed=network['ethernets'].pop('INTERFACE') %}{{network}}"
  when: network.ethernets is defined and network.ethernets.INTERFACE is defined

- name: Configuring Netplan
  template:
    src: etc/netplan/config.yaml.j2
    dest: "{{ netplan_config_file }}"
    mode: "{{ netplan_config_file_mode}}"
    backup: true
  become: true
  notify: netplan generate config
