---
- name: Include Netplan vars
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}-{{ansible_distribution_major_version}}.yaml'
        - '{{ansible_distribution}}.yaml'
        - '{{ansible_os_family}}.yaml'
        - default.yaml
      paths:
        - 'vars'

- name: Move content of INTERFACE to the correct interface name.
  set_fact:
    network: "{{ network | combine({'ethernets': { ansible_default_ipv4.interface : network['ethernets']['INTERFACE'] }}, recursive=True) }}"
  when: network.ethernets is defined and network.ethernets.INTERFACE is defined

- name: Remove the INTERFACE key 
  set_fact:
    network: "{% set removed=network['ethernets'].pop('INTERFACE') %}{{network}}"
  when: network.ethernets is defined and network.ethernets.INTERFACE is defined

- name: Configuring Netplan
  template:
    src: etc/netplan/config.yaml.j2
    dest: "{{ netplan_config_file }}"
    mode: "{{ netplan_config_file_mode}}"
    backup: true
  become: true
  when: netplan_configuration != []
  notify: netplan generate config
