---

network: 
  ethernets:
    INTERFACE:
      addresses:
      - "{{ hostvars[inventory_hostname].ansible_host }}/24"
      gateway4: "{{ default_gateway }}"
      nameservers: "{{ default_nameservers }}"
  version: 2